development:
  url: redis://localhost:6379/0
  pool_timeout: 5
  size: 10

test:
  url: redis://localhost:6379/1

production:
  url: <%= Rails.application.credentials.REDIS_URL || 'redis://localhost:6379/0' %>
  pool_timeout: 5
  size: <%= (Rails.application.credentials.REDIS_POOL_SIZE || 25).to_i %>